apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 3  # Set to 3 replicas for load balancing and availability
  selector:
    matchLabels:
      app: two-tier-app
  strategy:
    type: RollingUpdate  # Use rolling update strategy
    rollingUpdate:
      maxSurge: 1  # Allow one extra pod during update
      maxUnavailable: 1  # Allow one pod to be unavailable during update
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: rahul7600/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: mysql  # Use the MySQL service name
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "devops"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

