name: Docker Build and Push

on:
  push:
    branches:
      - master  # Trigger on pushes to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub using GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build . -t flaskapp

    # Step 4: Tag the image with your Docker Hub username
    - name: Tag Docker image
      run: |
        docker tag flaskapp rahul7600/flaskapp:v1

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push rahul7600/flaskapp:v1
